<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Redlime</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^`{3}$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.tag.source.redlime</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^`{3}$\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.tag.source.redlime</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.value.source.redlime</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.source.redlime</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.source.source.redlime</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\!)\s(.*?)\s</string>
			<key>name</key>
			<string>meta.header.table.source.redlime</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.source.redlime</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.shortcut.source.redlime</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.source.redlime</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.tag.source.redlime</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.tag.source.redlime</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment.tag.source.redlime</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)(\w+)(\])(\()([\w\s]+)(\))</string>
			<key>name</key>
			<string>meta.shortcut.source.redlime</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(#+)\s.*</string>
					<key>name</key>
					<string>markup.heading.source.redlime</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.source.redlime</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.bold.source.redlime</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*{2})(.*)(\*{2})</string>
					<key>name</key>
					<string>meta.bold.source.redlime</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.source.redlime</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.italic.source.redlime</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^|[^\*])(\*)([^\*]+)(\*)([^\*]|$)</string>
					<key>name</key>
					<string>meta.italic.source.redlime</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.priority-major.source.redlime</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.priority-critical.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s(Minor|Trivial|(Major)|(Critical))\s</string>
					<key>name</key>
					<string>string.priority.source.redlime</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s(?i:new|in progress|reopened|feedback|(resolved|code review|testing|stopped|closed))\s</string>
					<key>name</key>
					<string>string.status.source.redlime</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.redlime</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.source.redlime</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.redlime</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.tag.source.redlime</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.url.source.redlime</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>comment.tag.source.redlime</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(.*?)(\])(\()((http|https)://.*?)(\))</string>
					<key>name</key>
					<string>meta.attachment.source.redlime</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.redlime</string>
	<key>uuid</key>
	<string>d549dbff-027d-438c-b561-76f663a9d37f</string>
</dict>
</plist>
